/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import server.Server;

/**
 *
 * @author Dzaja
 */
public class ServerskaForma extends javax.swing.JFrame {

    Server server;

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        //server = new Server();
        lblStatusText.setText("ZAUSTAVLJEN");
        btnzaustaviSrv.setEnabled(false); // ako nije pokrenut ne sme se zaustavljati
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnzaustaviSrv = new javax.swing.JButton();
        pokreniSrv = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblStatusText = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnzaustaviSrv.setText("ZAUSTAVI SERVER");
        btnzaustaviSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzaustaviSrvActionPerformed(evt);
            }
        });

        pokreniSrv.setText("POKRENI SERVER");
        pokreniSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokreniSrvActionPerformed(evt);
            }
        });

        lblStatus.setText("STATUS");

        lblStatusText.setText("s");

        jMenu1.setText("KONFIGURACIJA");

        jMenuItem2.setText("baza");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("port");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(pokreniSrv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnzaustaviSrv)
                    .addComponent(lblStatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblStatusText))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnzaustaviSrv)
                    .addComponent(pokreniSrv))
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        KonfigBazaForm kbf = new KonfigBazaForm(this, false);
        kbf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        KonfigPortForm kpf = new KonfigPortForm(this, false);
        kpf.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void pokreniSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokreniSrvActionPerformed
        server = new Server();
        server.start();
        lblStatusText.setText("POKRENUT");
        btnzaustaviSrv.setEnabled(true); // kada je server pokrenut smemo da ga ugasimo
        pokreniSrv.setEnabled(false); // a kad je pokrenut ne moze se ponovo pokretati
    }//GEN-LAST:event_pokreniSrvActionPerformed

    private void btnzaustaviSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzaustaviSrvActionPerformed
        server.zaustaviServer();
        lblStatusText.setText("ZAUSTAVLJEN");
        btnzaustaviSrv.setEnabled(false); // kada je server ugasen ne smemo zaustavljati ponovo
        pokreniSrv.setEnabled(true); // a kad je zaustavljen moze se  pokretati
    }//GEN-LAST:event_btnzaustaviSrvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnzaustaviSrv;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusText;
    private javax.swing.JButton pokreniSrv;
    // End of variables declaration//GEN-END:variables
}
